package com.anfilofyev.stations;

public enum StationsEnum {

    BirstfeldenHard,
    Salinenstr,
    Schulstr,
    Baren,
    Breite,
    Waldenburgerstr,
    StAlbanTor,
    Aeschenplatz,
    Barfusserplatz,
    MusikAkademie,
    Universitat,
    Spalentor,
    Burgfelderplatz,
    Strassburgerallee,
    FelixPlatterSpital,
    Luzernerring,
    WaldighoferStr,
    Burgfelderhof,
    SaintExupery,
    PlaceMermoz,
    Soleil,
    SaintLouisGare,
    Pratteln,
    Bahnhofstr,
    Gempenstr,
    Kasteli,
    Lachmatt,
    Rothausstr,
    MuttenzDorf,
    Schutzenstr,
    ZumPark,
    Kappeli,
    Freidorf,
    StJakob,
    Zeughaus,
    KarlBarthPlatz,
    Grellingerstr,
    Sevogelplatz,
    Bankverein,
    Marktplatz,
    Schifflande,
    Rheingasse,
    Claraplatz,
    Clarastr,
    Riehenring,
    MusicalTheater,
    Brombacherstr,
    Dreirosenbrucke,
    Pilgerstr,

    BaselSBB

}
